name: Security & Quality Checks (Bun)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: TypeScript Check
        run: bun x tsc --noEmit

      - name: ESLint Check
        run: bun x eslint . --ext .ts,.tsx

      - name: Run Security Audit (npm-compatible)
        run: |
          bun pm ls > deps.txt
          echo "Dependencies listed, running npm audit as fallback"
          npm install --package-lock-only
          npm audit --audit-level=moderate || echo "Audit completed with warnings"

      - name: Dependency Vulnerability Check (OWASP style)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Secure NextJS Demo"
          scan: "."
          format: "HTML"
